Numpy Operation's

In [3]:

import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing :",arr[0:6])
print("Alternative :",arr[0:8:2])
print("Negative Indexing :",arr[-2])


Basic Slicing : [1 2 3 4 5 6]
Alternative : [1 3 5 7]
Negative Indexing : 9


In [ ]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element :",arr_2D[1,2])
print("Entie Row",arr_2D[1])
print("Entie Column",arr_2D[:, 1]) # (:) refers to entire thing 

Specific Element : 6
Entie Row [4 5 6]
Entie Column [2 5 8]


Sorting 

In [ ]:
Unsorted = np.array([5,9,7,4,6,2,3,1,7,6,9])
print("Sorted Array",np.sort(Unsorted))

arr_2D_Unsorted = np.array([[1,3,6],
                            [8,5,6],
                            [5,1,4]])
print("2D Array is Sored in Column:\n",np.sort(arr_2D_Unsorted,axis=0))

Sorted Array [1 2 3 4 5 6 6 7 7 9 9]
2D Array is Sored in Column:
 [[1 1 4]
 [5 3 6]
 [8 5 6]]


Filter 

In [4]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
EvenNumbers = numbers[numbers % 2== 0]
print("This are Even Numbers",EvenNumbers)

This are Even Numbers [ 2  4  6  8 10]


Filter with Mask

In [6]:
mask = numbers > 5
print("Numbers which are Greater than 5:",numbers[mask])

Numbers which are Greater than 5: [ 6  7  8  9 10]


Fancy Indexing vs np.whare

In [8]:
indices = [0,2,4]
print("The Indices are :",numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where ",numbers[where_result])

The Indices are : [1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


Adding and Removing 

In [ ]:
arr_1 = [1,2,3]
arr_2 = [4,5,6]

combine = np.concatenate((arr_1,arr_2))
print(combine)



[1 2 3 4 5 6]


Array Compatibility

In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6,6])
arr3 = np.array([7,8,9])

print("Compatibility Shape is :",arr1.shape == arr2.shape)


Compatibility Shape is : False


In [33]:
OriginalArr =np.array([[1,2,3],[4,5,6]])
new_row = np.array([[7,8,9]])

with_new_row = np.vstack((OriginalArr,new_row))
print(OriginalArr,"\n")
print(with_new_row,"\n")

new_col = np.array([[2],[5]])
with_new_col = np.hstack((OriginalArr, new_col))
print(with_new_col)

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3 2]
 [4 5 6 5]]


Deleting

In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9])
delted = np.delete(arr,5)
print(delted)

[1 2 3 4 5 7 8 9]
