In [1]:
import numpy as np
import time

Creation of Array from List  in Python

In [2]:
arr_1 = np.array([1,4,3])
print("Array-1",arr_1)

arr_2 = np.array([[1,4,3],[3,1,4]])
print("Array-2",arr_2)


Array-1 [1 4 3]
Array-2 [[1 4 3]
 [3 1 4]]


Multiplication

In [5]:
list = (1,2,3)
print("List Multiplication :",list)

arr = np.array([1,2,3]) #Element wise Multiplication
print("Array Multiplication :",arr*2)


List Multiplication : (1, 2, 3)
Array Multiplication : [2 4 6]


Efficiency of Time in List (or) Array

In [10]:
#In List
start = time.time()
py_list = [1 * 2 for i in range(1000000)]
print("\n List Operation Time :", time.time() - start)
#In Numpy
start = time.time()
py_arr = np.arange(1000000) * 2
print("\n Numpy Operation Time :", time.time() - start)


 List Operation Time : 0.0301055908203125

 Numpy Operation Time : 0.011432647705078125


Creating Different Types of Array's in Numpy

In [20]:
Zero = np.zeros((4,5))
print("Zero's Array :\n",Zero)

Ones = np.ones((4,4))
print("\nOnes's Array :\n",Ones)

Full = np.full((4,4),3) #To print a Specific Number
print("\nFull's Array :\n",Full)

Random = np.random.random((2,3))
print("\nRandom's Array :\n",Random)


Zero's Array :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones's Array :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Full's Array :
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]

Random's Array :
 [[0.82919536 0.64559685 0.27558554]
 [0.85815852 0.13474394 0.53668303]]


Vector - Matrices - Tensor

In [26]:
Vector = np.array([1,2,3,4,5])
print("Vector's: ",Vector)

Matrix = np.array([[1,2,3,4],
                    [5,6,7,8]])
print("\nMatrices's: ",Matrix)

Tensor = np.array([[1,2,3],[4,5,6], #This a Multi-Dimensional Array 
                   [7,8,9],[1,2,3]]) 
print("\nTensor:",Tensor)

Vector's:  [1 2 3 4 5]

Matrices's:  [[1 2 3 4]
 [5 6 7 8]]

Tensor: [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


Array Properties

In [27]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape: ",arr.shape) #It Gives you Rows and Columns
print("Dimension: ",arr.ndim) #It Gives you Dimension
print("Size: ",arr.size) #It Gives you Total number of Elements
print("Data Type: ",arr.dtype) #It Gives you Type of DataType

Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


Array Reshaping

In [39]:
arr = np.arange(16)
print("Original Array:",arr)

reshaped = arr.reshape([4,4])
print("\nReshaped Array:\n",reshaped)

Flattened = reshaped.flatten()
print("\nFlatten Array:\n",Flattened)
 
#Gives you (Returns Original View,Instead of Copy) 
Raveled = reshaped.ravel()
print("\nRaveled Array:\n",Raveled)

Transpose = reshaped.transpose()
print("\nTransposed Array:\n",Transpose)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Flatten Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Raveled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Transposed Array:
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
